// Generated by CoffeeScript 1.12.6
(function() {
  var App;
  var url = "http://92.222.34.194:4000/";

  App = {};


  /*
  	Init
   */

  App.init = function() {
    App.canvas = document.createElement('canvas');
    App.canvas.height = 500;
    App.canvas.width = 800;
    document.getElementsByTagName('article')[0].appendChild(App.canvas);
    App.ctx = App.canvas.getContext("2d");
    App.ctx.fillStyle = "solid";
    App.ctx.strokeStyle = "#021E6D";
    App.ctx.lineWidth = 5;
    App.ctx.lineCap = "round";
    App.socket = io.connect(url);
    App.socket.on('draw', function(data) {
      return App.draw(data.x, data.y, data.type);
    });
    App.draw = function(x, y, type) {
      if (type === "dragstart") {
        App.ctx.beginPath();
        return App.ctx.moveTo(x, y);
      } else if (type === "drag") {
        App.ctx.lineTo(x, y);
        return App.ctx.stroke();
      } else {
        return App.ctx.closePath();
      }
    };
  };


  /*
  	Draw Events
   */

  $('canvas').live('drag dragstart dragend', function(e) {
    var currentElement, totalOffsetX, totalOffsetY, type, x, y;
    totalOffsetX = 0;
    totalOffsetY = 0;
    currentElement = e.currentTarget;
    type = e.handleObj.type;
    while (true) {
      totalOffsetX += currentElement.offsetLeft - currentElement.scrollLeft;
      totalOffsetY += currentElement.offsetTop - currentElement.scrollTop;
      currentElement = currentElement.offsetParent;
      if (currentElement == null) {
        break;
      }
    }
    x = e.pageX - totalOffsetX;
    y = e.pageY - totalOffsetY;
    App.draw(x, y, type);
    App.socket.emit('drawClick', {
      x: x,
      y: y,
      type: type
    });
  });

  $(function() {
    return App.init();
  });

}).call(this);
